{% set name = "anaconda-assistant-sdk" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/anaconda_assistant_sdk-{{ version }}.tar.gz
  sha256: 1bf4b513bab7402faa126874e2ef0c2adb5ddd8a8484c320b239cad4a01c4ad0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs >=0.3
    - setuptools-scm >=7.1
    - pip
  run:
    - python >={{ python_min }}
    - anaconda-auth >=0.8
    - anaconda-cli-base >=0.5
    - pydantic
  run_constrained:
    - langchain-core >=0.3
    - llm >=0.22

test:
  imports:
    - anaconda_assistant
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  summary: The Anaconda Assistant Python client
  doc_url: https://anaconda.github.io/assistant-sdk/sdk
  dev_url: https://github.com/anaconda/assistant-sdk
  home: https://anaconda.com
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AlbertDeFusco
